version: '3'
services:
  db:
    image: postgres:latest
  web:
    build: .
    command: python3 /app/fontes/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/fontes
    ports:
      - "8000:8000"
    depends_on:
      - db
